name: app
description: "DIMA project"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0
  csv: ^5.0.1
  cupertino_icons: ^1.0.8
  path_provider: ^2.0.11
  mockito: ^5.0.16

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/exercises.csv