name: Flutter CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Install Flutter
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.7.0'  

    # Step 3: Install dependencies
    - name: Install dependencies
      run: cd app && flutter pub get

    # Step 4: Run the tests
    - name: Run tests
      run: cd app && flutter test
